package com.github.jakz.openmom.lbx;

public enum LBXID
{
  ARMYLIST("armylist", true),
  BACKGRND("backgrnd", true),
  BOOK("book", true),
  BUILDDAT("builddat"),
  BUILDESC("buildesc"),
  CHRIVER("chriver"),
  CITYNAME("cityname"),
  CITYSCAP("cityscap"),
  CITYWALL("citywall"),
  CMBDESRC("cmbdesrc"),
  CMBDESRT("cmbdesrt"),
  CMBGRASC("cmbgrasc"),
  CMBGRASS("cmbgrass"),
  CMBMAGIC("cmbmagic"),
  CMBMOUNC("cmbmounc"),
  CMBMOUNT("cmbmount"),
  CMBTCITY("cmbtcity"),
  CMBTFX("cmbtfx"),
  CMBTSND("cmbtsnd"),
  CMBTUNDC("cmbtundc"),
  CMBTUNDR("cmbtundr"),
  CMBTWALL("cmbtwall"),
  COMBAT("combat"),
  COMPIX("compix"),
  CONQUEST("conquest"),
  DESC("desc"),
  DESERT("desert"),
  DIPLOMAC("diplomac"),
  DIPLOMSG("diplomsg"),
  EVENTMSG("eventmsg"),
  EVENTS("events"),
  FIGURES1("figures1"),
  FIGURES2("figures2"),
  FIGURES3("figures3"),
  FIGURES4("figures4"),
  FIGURES5("figures5"),
  FIGURES6("figures6"),
  FIGURES7("figures7"),
  FIGURES8("figures8"),
  FIGURES9("figures9"),
  FIGURE10("figure10"),
  FIGURE11("figure11"),
  FIGURE12("figure12"),
  FIGURE13("figure13"),
  FIGURE14("figure14"),
  FIGURE15("figure15"),
  FIGURE16("figure16"),
  FONTS("fonts"),
  HALOFAM("halofam"),
  HELP("help"),
  HERODATA("herodata"),
  HIRE("hire"),
  HLPENTRY("hlpentry"),
  INTRO("intro"),
  INTROSFX("introsfx"),
  INTROSND("introsnd"),
  ITEMDATA("itemdata"),
  ITEMISC("itemisc", true),
  ITEMPOW("itempow"),
  ITEMS("items"),
  LILWIZ("lilwiz"),
  LISTDAT("listdat"),
  LOAD("load"),
  LOSE("lose"),
  MAGIC("magic"),
  MAIN("main"),
  MAINSCRN("mainscrn"),
  MAPBACK("mapback"),
  MESSAGE("message"),
  MONSTER("monster"),
  MOODWIZ("moodwiz"),
  MUSIC("music"),
  NAMES("names"),
  NEWGAME("newgame"),
  NEWSOUND("newsound"),
  PORTRAIT("portrait"),
  RELOAD("reload"),
  RESOURCE("resource"),
  SCROLL("scroll"),
  SNDDRV("snddrv"),
  SOUNDFX("soundfx"),
  SPECFX("specfx"),
  SPECIAL("special", true),
  SPECIAL2("special2", true),
  SPELLDAT("spelldat"),
  SPELLOSE("spellose"),
  SPELLS("spells"),
  SPELLSCR("spellscr"),
  SPLMASTR("splmastr"),
  TERRAIN("terrain"),
  TERRSTAT("terrstat"),
  TERRTYPE("terrtype"),
  TUNDRA("tundra"),
  UNITS1("units1", true),
  UNITS2("units2", true),
  UNITVIEW("unitview"),
  VORTEX("vortex"),
  WALLRISE("wallrise"),
  WIN("win"),
  WIZARDS("wizards"),
  WIZLAB("wizlab"),
  ;
  
  public final String path;
  public final boolean isGfx;
  
  private LBXID(String name, boolean isGfx) { path = name; this.isGfx = isGfx; }
  private LBXID(String name) { this(name, false); }
};