#include "Race.h"

#include "Localization.h"

const Race Race::races[] = {
  {RACE_BARBARIANS,I18_RACE_NAME_BARBARIANS, I18_UNIT_NAME_BARBARIANS, HOUSE_MUD, 20, 0.15f},
  {RACE_BEASTMEN,I18_RACE_NAME_BEASTMEN, I18_UNIT_NAME_BEASTMEN, HOUSE_MUD, 0, 0.05f},
  {RACE_DARK_ELVES,I18_RACE_NAME_DARK_ELVES, I18_UNIT_NAME_DARK_ELVES, HOUSE_MUD, -20, 0.02f},
  {RACE_DRACONIANS,I18_RACE_NAME_DRACONIANS, I18_UNIT_NAME_DRACONIANS, HOUSE_MUD, -10, 0.05f},
  {RACE_DWARVES,I18_RACE_NAME_DWARVES, I18_UNIT_NAME_DWARVES, HOUSE_MUD, -20, 0.07f},
  {RACE_GNOLLS,I18_RACE_NAME_GNOLLS, I18_UNIT_NAME_GNOLLS, HOUSE_MUD, -10, 0.05f},
  {RACE_HALFLINGS,I18_RACE_NAME_HALFLINGS, I18_UNIT_NAME_HALFLINGS, HOUSE_MUD, 0, 0.15f},
  {RACE_HIGH_ELVES,I18_RACE_NAME_HIGH_ELVES, I18_UNIT_NAME_HIGH_ELVES, HOUSE_MUD, -20, 0.05f},
  {RACE_HIGH_MEN,I18_RACE_NAME_HIGH_MEN, I18_UNIT_NAME_HIGH_MEN, HOUSE_MUD, 0, 0.10f},
  {RACE_KLACKONS,I18_RACE_NAME_KLACKONS, I18_UNIT_NAME_KLACKONS, HOUSE_MUD, -20, 0.05f},
  {RACE_LIZARDMEN,I18_RACE_NAME_LIZARDMEN, I18_UNIT_NAME_LIZARDMEN, HOUSE_MUD, 10, 0.10f},
  {RACE_NOMADS,I18_RACE_NAME_NOMADS, I18_UNIT_NAME_NOMADS, HOUSE_MUD, -10, 0.10f},
  {RACE_ORCS,I18_RACE_NAME_ORCS, I18_UNIT_NAME_ORCS, HOUSE_MUD, 0, 0.10f},
  {RACE_TROLLS,I18_RACE_NAME_TROLLS, I18_UNIT_NAME_TROLLS, HOUSE_MUD, -20, 0.03f}
};