#include "Race.h"

#include "Localization.h"

const Race Race::races[] = {
  {RaceID::BARBARIANS,I18::RACE_NAME_BARBARIANS, I18::UNIT_NAME_BARBARIANS, HOUSE_MUD, 20, 0.15f},
  {RaceID::BEASTMEN,I18::RACE_NAME_BEASTMEN, I18::UNIT_NAME_BEASTMEN, HOUSE_MUD, 0, 0.05f},
  {RaceID::DARK_ELVES,I18::RACE_NAME_DARK_ELVES, I18::UNIT_NAME_DARK_ELVES, HOUSE_MUD, -20, 0.02f},
  {RaceID::DRACONIANS,I18::RACE_NAME_DRACONIANS, I18::UNIT_NAME_DRACONIANS, HOUSE_MUD, -10, 0.05f},
  {RaceID::DWARVES,I18::RACE_NAME_DWARVES, I18::UNIT_NAME_DWARVES, HOUSE_MUD, -20, 0.07f},
  {RaceID::GNOLLS,I18::RACE_NAME_GNOLLS, I18::UNIT_NAME_GNOLLS, HOUSE_MUD, -10, 0.05f},
  {RaceID::HALFLINGS,I18::RACE_NAME_HALFLINGS, I18::UNIT_NAME_HALFLINGS, HOUSE_MUD, 0, 0.15f},
  {RaceID::HIGH_ELVES,I18::RACE_NAME_HIGH_ELVES, I18::UNIT_NAME_HIGH_ELVES, HOUSE_MUD, -20, 0.05f},
  {RaceID::HIGH_MEN,I18::RACE_NAME_HIGH_MEN, I18::UNIT_NAME_HIGH_MEN, HOUSE_MUD, 0, 0.10f},
  {RaceID::KLACKONS,I18::RACE_NAME_KLACKONS, I18::UNIT_NAME_KLACKONS, HOUSE_MUD, -20, 0.05f},
  {RaceID::LIZARDMEN,I18::RACE_NAME_LIZARDMEN, I18::UNIT_NAME_LIZARDMEN, HOUSE_MUD, 10, 0.10f},
  {RaceID::NOMADS,I18::RACE_NAME_NOMADS, I18::UNIT_NAME_NOMADS, HOUSE_MUD, -10, 0.10f},
  {RaceID::ORCS,I18::RACE_NAME_ORCS, I18::UNIT_NAME_ORCS, HOUSE_MUD, 0, 0.10f},
  {RaceID::TROLLS,I18::RACE_NAME_TROLLS, I18::UNIT_NAME_TROLLS, HOUSE_MUD, -20, 0.03f}
};